---
title: "Randy Clarke's CV"
author: Randy Clarke
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results='asis')
library(tidyverse)
library(glue)

source('parsing_functions.R')

position_data <- read_csv('positions.csv', show_col_types = FALSE)

# Define PDF_EXPORT (you can set this to TRUE when you want to export to PDF)
PDF_EXPORT <- FALSE

# Initialize links vector
links <- c()
```


Aside
================================================================================

```{r}
if(PDF_EXPORT){
  cat("View this CV online with links at [rclar.github.io/cv](https://rclar.github.io/cv)")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/rclar/cv/raw/main/clarke_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r, results='asis'}
contact_info <- "
- <i class='fa fa-envelope'></i> rclar6294@gmail.com  
- <i class='fa fa-phone'></i> 908-875-7393  
- <i class='fa fa-github'></i> [github.com/rclar](https://github.com/rclar)  
- <i class='fa fa-linkedin'></i> [linkedin.com/in/randytclarke](https://linkedin.com/in/randytclarke)  
- <i class='fa fa-map-marker'></i> Tempe, Arizona, United States
"
cat(contact_info)
```
--------------------------------------------------------------------------------

```{r}
skills <- tribble(
  ~skill,               ~level,
  "R",                  5,
  "Slack",              5,
  "Google Workspace",   4,
  "Adobe Suite",        4,
  "NGP VAN",            4,
  "Salesforce",         3,
  "AWS",                3
)

build_skill_bars(skills)
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [github.com/nstrayer/cv](https://github.com/nstrayer/cv).

Last updated on `r Sys.Date()`.




Main
================================================================================

Randy Clarke {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- "Community engagement professional with extensive experience in political campaigns, voter mobilization, and customer success. Skilled in recruiting, training, and managing volunteers, developing and executing outreach initiatives, and using data-driven strategies to optimize campaign effectiveness."

cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```



Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------
::: aside
I have worked in various roles in political campaigns, community engagement, and customer service. I thrive in collaborative environments where I can make a positive impact and continuously learn.
:::

```{r}
print_section(position_data, 'industry_positions')
```

<br>
<br>
<br>


Skills & Certifications {data-icon=certificate}
--------------------------------------------------------------------------------

::: aside
I continuously develop my skills to stay current with industry trends and best practices.
:::

```{r}
skills <- c("Data Collection and Management", "Software as a Service (SaaS)", "Client Relationship Management", "Community Organizing", "Strategic Communication", "Volunteer Management")

cat("### Skills\n")
cat(paste("- ", skills, collapse = "\n"))

cat("\n\n### Certifications\n")
cat("- IRB – Social and Behavioral Research (Group 2)\n")
cat("- Arena Academy 201\n")
```


Technical Proficiencies {data-icon=laptop-code}
--------------------------------------------------------------------------------

```{r}
tech_skills <- c("Salesforce", "R", "Adobe Creative Cloud", "Google Workspace", "Microsoft Office", "STATA", "SPSS", "NGP Van", "Question Pro", "Scale To Win", "Impactive", "Mobilize")

cat(paste("- ", tech_skills, collapse = "\n"))
```




```{r}
if(PDF_EXPORT){
  cat("
  
Links {data-icon=link}
--------------------------------------------------------------------------------

<br>


")
  
  walk2(links, 1:length(links), function(link, index){
    print(glue('{index}. {link}'))
  })
}
```


